<?xml version="1.0" encoding="utf-8"?><Database Name="DB" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\LocalDBDemo;Initial Catalog=DB;Integrated Security=True" SettingsObjectName="VirtualLibrary.Properties.Settings" SettingsPropertyName="DBConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bookinfo" Member="Bookinfos">
    <Type Name="Bookinfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Edition" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>